### ISSUE TITLE
[Events] Push notifications for upcoming events

### ISSUE THREAD

**Issue by svenvanhal** [WISVCH/website#19]
See: https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API

**Comment by TimvdLippe** [comment]
The notification API is really nice, but it is tricky to get right. Most notably, you want to prevent spam of users, only pushing the most important events. I advise you to consider the algorithm very carefully before implementing, because a wrong implementation means users will deter to use it.

**Comment by TimvdLippe** [comment]
This is a nice talk that addresses some points: https://www.youtube.com/watch?v=uh0IASBexdM
