### ISSUE TITLE
Profile > change address is broken

### ISSUE THREAD

**Issue by svenvanhal** [WISVCH/website#40]

**Comment by sanderploegsma** [comment]
Hoe krijg ik nu mijn machazines binnen? 😢

**Comment by svenvanhal** [comment]
Oh heb dit paar dagen terug toevallig uitgezocht, komt omdat het `www-data` account in de container geen mails (meer?) kan versturen. Heb de oplossing alleen nog niet gevonden.

**Comment by praseodym** [comment]
Kun je Wordpress niet gewoon over SMTP (`ch.tudelft.nl`) laten mailen?

**Comment by sudharshankr** [comment]
Am still facing this issue. Is there any other way to update my address with CH?

**Comment by praseodym** [comment]
> Am still facing this issue. Is there any other way to update my address with CH?

You can send an email to board@ch.tudelft.nl.
