### ISSUE TITLE
PHP error on CHoice page

### ISSUE THREAD

**Issue by praseodym** [WISVCH/website#42]
https://ch.tudelft.nl/education/choice-old-exams/

```
Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/wp-includes/post-template.php on line 284
```

![screenshot_2019-01-06_17-45-43](https://user-images.githubusercontent.com/20283/50739068-eb50e200-11da-11e9-8bf6-b62ff5b393c7.png)

**Comment by svenpopping** [comment]
https://ch.tudelft.nl/career/overview/ has the same error

**Comment by elarb** [comment]
Some on https://ch.tudelft.nl/activities/
