### ISSUE TITLE
Webshop knop verbergen bij book sale

### ISSUE THREAD

**Issue by kgimbergh** [WISVCH/website#52]
Momenteel kan iedereen die de book sale website opent bij de webshop. Voorheen moest je eerst inloggen voordat je de knop 'webshop' kon zien. Aangezien wij boeken met korting willen leveren voor alleen onze leden, zou ik graag willen zien dat deze knop weer verborgen wordt voor niet-leden.

**Comment by JoepdeJong** [comment]
done.
